/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./../components/el/inputBox-opshell copy.vue')['default']
    ElBtn: typeof import('./../components/el/btn.vue')['default']
    ElCheckbox: typeof import('./../components/el/checkbox.vue')['default']
    ElDatePicker: typeof import('./../components/el/datePicker.vue')['default']
    ElDivider: typeof import('./../components/el/divider.vue')['default']
    ElDrag: typeof import('./../components/el/drag.vue')['default']
    ElEditor: typeof import('./../components/el/editor.vue')['default']
    ElImg: typeof import('./../components/el/img.vue')['default']
    ElInput: typeof import('./../components/el/input.vue')['default']
    ElInputBox: typeof import('./../components/el/inputBox.vue')['default']
    ElInputBoxOpshell: typeof import('./../components/el/inputBox-opshell.vue')['default']
    ElJodit: typeof import('./../components/el/jodit.vue')['default']
    ElLineProgress: typeof import('./../components/el/lineProgress.vue')['default']
    ElLoadingOverlay: typeof import('./../components/el/loadingOverlay.vue')['default']
    ElProgress: typeof import('./../components/el/progress.vue')['default']
    ElRadio: typeof import('./../components/el/radio.vue')['default']
    ElSelect: typeof import('./../components/el/select.vue')['default']
    ElSvgIcon: typeof import('./../components/el/svgIcon.vue')['default']
    ElTips: typeof import('./../components/el/tips.vue')['default']
    ElUploader: typeof import('./../components/el/uploader.vue')['default']
    MoleCalendar: typeof import('./../components/mole/calendar.vue')['default']
    MoleColorList: typeof import('./../components/mole/colorList.vue')['default']
    MoleConfirm: typeof import('./../components/mole/confirm.vue')['default']
    MoleDatePicker: typeof import('./../components/mole/datePicker.vue')['default']
    MoleImageUploader: typeof import('./../components/mole/imageUploader.vue')['default']
    MoleImgUpload: typeof import('./../components/mole/ImgUpload.vue')['default']
    MoleListBar: typeof import('./../components/mole/listBar.vue')['default']
    MoleModalHeader: typeof import('./../components/mole/modalHeader.vue')['default']
    MoleNotify: typeof import('./../components/mole/notify.vue')['default']
    MoleTreeItem: typeof import('./../components/mole/treeItem.vue')['default']
    MoleWaterfallsFlowCard: typeof import('./../components/mole/waterfallsFlowCard.vue')['default']
    OrgaContentBlock: typeof import('./../components/orga/contentBlock.vue')['default']
    OrgaFooter: typeof import('./../components/orga/footer.vue')['default']
    OrgaHeader: typeof import('./../components/orga/header.vue')['default']
    OrgaList: typeof import('./../components/orga/list.vue')['default']
    OrgaLogin: typeof import('./../components/orga/login.vue')['default']
    OrgaModal: typeof import('./../components/orga/modal.vue')['default']
    OrgaNav: typeof import('./../components/orga/nav.vue')['default']
    OrgaPagination: typeof import('./../components/orga/pagination.vue')['default']
    OrgaSideMenu: typeof import('./../components/orga/sideMenu.vue')['default']
    OrgaSwiper: typeof import('./../components/orga/swiper.vue')['default']
    OrgaSystem: typeof import('./../components/orga/system.vue')['default']
    OrgaWaterfallsFlow: typeof import('./../components/orga/waterfallsFlow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
